"""
env.py

Environment interface for MAPPO.

This file is the ONLY place that interacts with CybORG.
The rest of the project only imports CC4Env.

Ground truth
------------

get_ground_truth() is a heuristic, not a perfect oracle: for a given
sender agent, it checks whether any red-agent session exists on a host
within that agent's assigned subnets, per the CURRENT true state. This
is enough to give DynamicTrust a real (non-null) correctness signal --
"did this agent report a compromise when one actually existed in its
zone" -- but it does not yet distinguish SCAN vs COMPROMISE vs
LATERAL_MOVEMENT, or identify a specific target host. Refine using
state.hosts[h].events (old_process_creation / process_creation,
old_network_connections / network_connections -- see
BlueFlatWrapper._get_procesess / _get_connections for the exact
pattern) if you need finer-grained event_type ground truth later.
"""

from CybORG import CybORG
from CybORG.Agents import (
    SleepAgent,
    EnterpriseGreenAgent,
    FiniteStateRedAgent,
)
from CybORG.Simulator.Scenarios import EnterpriseScenarioGenerator
from CybORG.Agents.Wrappers import EnterpriseMAE

from .config import EPISODE_LENGTH
# from .communication.schema import EventType, HostStatus, ThreatLevel
from .communication.schema import (
    EventType,
    HostStatus,
    ThreatLevel,
    TargetType,
)


class CC4Env:

    def get_num_targets(self):
            """
            Return the number of possible communication targets.

            Target IDs use the deterministic mapping:

                sorted(state.hosts.keys())

            Therefore the target vocabulary size is the number
            of hosts currently known to CybORG.
            """

            state = self.cyborg.environment_controller.state

            hostnames = sorted(state.hosts.keys())

            return len(hostnames)

    def __init__(self, red_agent_class=FiniteStateRedAgent):

        scenario = EnterpriseScenarioGenerator(
            blue_agent_class=SleepAgent,
            green_agent_class=EnterpriseGreenAgent,
            red_agent_class=red_agent_class,
            steps=EPISODE_LENGTH,
        )

        cyborg = CybORG(scenario_generator=scenario)

        # Kept so get_ground_truth() (and anything else that needs true
        # state) can reach environment_controller.state directly, the
        # same way TrueStateTableWrapper does. Previously this was a
        # local variable in __init__ and was lost after construction.
        self.cyborg = cyborg

        # Official CC4 MARL wrapper
        self.env = EnterpriseMAE(cyborg)

        self.agent_names = list(self.env.agents)

        # ------------------------------------------------------------
        # Ground-truth compromise snapshot -- see step() / reset() and
        # get_ground_truth() below for why this has to be captured
        # BEFORE each env.step() call rather than read live.
        # ------------------------------------------------------------

        self._pre_step_compromised_hosts = self._compute_compromised_hosts()

    ############################################################

    def reset(self, seed=None):

        observations, info = self.env.reset(seed=seed)

        # Fresh episode -- re-snapshot from the post-reset state so
        # the first messages generated this episode are graded
        # against the state they actually saw.
        self._pre_step_compromised_hosts = self._compute_compromised_hosts()

        return observations, info

    ############################################################

    def step(self, actions, messages=None):

        if messages is None:
            messages = {}

        # ------------------------------------------------------------
        # Snapshot ground truth BEFORE stepping.
        #
        # Messages arriving in this call were generated by train.py
        # from the observation as of the START of this call (i.e.
        # right after the PREVIOUS step/reset) -- see get_ground_truth()
        # for the full explanation. self.cyborg.environment_controller
        # .state is mutated in place by self.env.step() below, so this
        # has to run first or get_ground_truth() ends up grading
        # messages against a state that didn't exist yet when they
        # were written.
        # ------------------------------------------------------------

        self._pre_step_compromised_hosts = self._compute_compromised_hosts()

        observations, rewards, terminated, truncated, info = \
            self.env.step(actions, messages)

        return (
            observations,
            rewards,
            terminated,
            truncated,
            info,
        )

    @property
    def agents(self):

        return self.env.agents

    @property
    def possible_agents(self):

        return self.env.possible_agents

    def observation_space(self, agent):

        return self.env.observation_space(agent)

    def action_space(self, agent):

        return self.env.action_space(agent)

    def sample_actions(self):
        """
        Random action for every blue agent.
        Useful for testing.
        """

        actions = {}

        for agent in self.agents:
            actions[agent] = self.action_space(agent).sample()

        return actions

    def get_observation_dims(self):
        dims = {}
        for agent in self.agents:
            dims[agent] = self.observation_space(agent).shape[0]

        return dims

    ############################################################

    def get_action_dims(self):

        dims = {}

        for agent in self.agents:
            dims[agent] = self.action_space(agent).n

        return dims

    ############################################################
    # Passthrough: action-space introspection
    #
    # Needed by action_mask.py to build the Adaptive Action Mask
    # without any file outside env.py touching CybORG directly.
    ############################################################

    def action_mask(self, agent_name):
        """
        Structural validity mask for `agent_name`, as maintained by
        CybORG's BlueFixedActionWrapper.

        True  -> action at this index currently targets a real
                 host/subnet that exists this episode.
        False -> action is a padding/no-op placeholder (e.g. the
                 target host was not generated this episode).

        This is recomputed by CybORG at every env.reset() (see
        BlueFixedActionWrapper._populate_action_space), so it is
        already episode-fresh -- it does NOT change mid-episode.
        """

        return self.env.action_mask(agent_name)

    def action_labels(self, agent_name):
        """Human-readable label per action index (for logging/debugging)."""

        return self.env.action_labels(agent_name)

    def actions(self, agent_name):
        """Ordered list of the underlying CybORG Action objects."""

        return self.env.actions(agent_name)

    ############################################################
    # Live, agent-legitimate signals for the Adaptive Action Mask
    #
    # Both of the following are re-derived directly from CybORG's
    # host-event log -- the SAME event data BlueFlatWrapper.observation_change
    # projects into `malicious_processes` / `network_connections` in the
    # agent's own observation vector. This is NOT privileged red-team
    # ground truth (unlike get_ground_truth() below, which is only used
    # for trust supervision) -- it is exactly what the agent already
    # "sees", just re-read here instead of re-parsed out of a padded,
    # per-subnet-flattened observation array.
    ############################################################

    def get_host_alert_flags(self, agent_name):
        """
        Return {hostname: bool} for every host this agent's action space
        can target (routers excluded, they are never action targets).

        True means the host currently has an outstanding malicious-process
        or suspicious-network-connection event -- i.e. it is currently
        "flagged" from the agent's own point of view.
        """

        state = self.cyborg.environment_controller.state

        flags = {}

        for hostname in self.env.hosts(agent_name):

            if "router" in hostname:
                continue

            if hostname not in state.hosts:
                flags[hostname] = False
                continue

            events = state.hosts[hostname].events

            has_process_event = bool(
                events.old_process_creation or events.process_creation
            )

            has_connection_event = bool(
                events.old_network_connections or events.network_connections
            )

            flags[hostname] = has_process_event or has_connection_event

        return flags

    def get_zone_alert_flags(self, agent_name):
        """
        Return {subnet_name: bool}: True if ANY host in that subnet is
        currently flagged (see get_host_alert_flags). Used to gate
        BlockTrafficZone so an agent cannot cut off a zone with no
        observed malicious activity.
        """

        state = self.cyborg.environment_controller.state

        host_flags = self.get_host_alert_flags(agent_name)

        zone_flags = {}

        for hostname, flagged in host_flags.items():

            subnet = state.hostname_subnet_map.get(hostname)

            if subnet is None:
                continue

            subnet = str(subnet).lower()

            zone_flags[subnet] = zone_flags.get(subnet, False) or flagged

        return zone_flags

    ############################################################
    # Ground truth for MessageEvaluator / DynamicTrust
    ############################################################

    def _compute_compromised_hosts(self):
        """
        Return the set of hostnames that CURRENTLY have an active Red
        session, per the live CybORG true state at the moment this is
        called.

        This is the expensive part of get_ground_truth()'s old
        per-(sender, receiver) loop, factored out so it runs ONCE per
        step() (from a single, correctly-timed snapshot) instead of
        being recomputed from scratch for every one of the up to
        NUM_AGENTS*(NUM_AGENTS-1) sender/receiver pairs graded per
        step -- a nice side effect of fixing the timing bug below.
        """

        state = self.cyborg.environment_controller.state

        compromised = set()

        for hostname, host in state.hosts.items():

            sessions = getattr(host, "sessions", {})

            for owner, session_list in sessions.items():

                if "red" in str(owner).lower() and session_list:
                    compromised.add(hostname)
                    break

        return compromised

    def get_ground_truth(
            self,
            sender_id,
            receiver_id,
            message,
            previous_info,
            current_info,
        ):
            """
            Training-side ground truth for one sender's structured message.

            The ground truth is derived from the CybORG true state as of
            the START of the step() call that delivered this message --
            i.e. the same state the sender's observation (and therefore
            the message itself) was actually generated from. This is
            captured by _compute_compromised_hosts() in step()/reset()
            BEFORE the environment advances, specifically so a message
            can't be graded against consequences (new compromises, red
            lateral movement, etc.) that happened on the SAME step,
            after the message was already written.

            For the sender's assigned subnets, this function identifies
            compromised hosts containing an active Red session.

            Returns information compatible with MessageEvaluator:

                event_type
                target_type
                target_id
                threat_level
                status
                compromised
                suspicious

            target_id uses the deterministic sorted host list:

                sorted(state.hosts.keys())

            This MUST remain consistent with the target-ID mapping used by
            the communication encoder/decoder.
            """

            # ------------------------------------------------------------
            # Resolve sender
            # ------------------------------------------------------------

            agent_names = sorted(self.possible_agents)

            if not (0 <= sender_id < len(agent_names)):
                return None

            sender_name = agent_names[sender_id]

            # ------------------------------------------------------------
            # Access true CybORG state
            # ------------------------------------------------------------

            state = self.cyborg.environment_controller.state

            agent_meta = state.scenario.agents.get(
                sender_name
            )

            if agent_meta is None:
                return None

            # ------------------------------------------------------------
            # Sender's assigned subnets
            # ------------------------------------------------------------

            sender_subnets = {
                str(subnet).lower()
                for subnet in agent_meta.allowed_subnets
            }

            # ------------------------------------------------------------
            # Deterministic host -> target_id mapping
            #
            # IMPORTANT:
            # This mapping must match the mapping used by the
            # communication module.
            # ------------------------------------------------------------

            hostnames = sorted(
                state.hosts.keys()
            )

            host_to_id = {
                hostname: index
                for index, hostname in enumerate(hostnames)
            }

            # ------------------------------------------------------------
            # Find compromised hosts in sender's zone
            #
            # Uses the snapshot captured BEFORE this step's env.step()
            # ran (see step()/_compute_compromised_hosts()) -- NOT a
            # fresh live query -- so this message is graded against the
            # state it was actually generated from, not whatever the
            # true state has since become.
            # ------------------------------------------------------------

            compromised_hosts = []

            for hostname in self._pre_step_compromised_hosts:

                subnet = state.hostname_subnet_map.get(
                    hostname
                )

                if subnet is None:
                    continue

                if str(subnet).lower() not in sender_subnets:
                    continue

                compromised_hosts.append(
                    hostname
                )

            # ------------------------------------------------------------
            # No compromise in sender's zone
            # ------------------------------------------------------------

            if not compromised_hosts:

                return {
                    "event_type": EventType.NONE,

                    "target_type": TargetType.NONE,

                    "target_id": 0,

                    "threat_level": ThreatLevel.LOW,

                    "status": HostStatus.NORMAL,

                    "compromised": False,

                    "suspicious": False,

                    "useful": False,
                }

            # ------------------------------------------------------------
            # Compromise exists
            #
            # For now we use the first deterministic compromised host.
            #
            # Later we can upgrade this to evaluate multiple targets.
            # ------------------------------------------------------------

            compromised_hosts.sort()

            target_hostname = compromised_hosts[0]

            target_id = host_to_id[
                target_hostname
            ]

            return {
                "event_type": EventType.COMPROMISE,

                "target_type": TargetType.HOST,

                "target_id": target_id,

                "threat_level": ThreatLevel.HIGH,

                "status": HostStatus.COMPROMISED,

                "compromised": True,

                "suspicious": False,

                "useful": True,
            }


from ray.tune.registry import register_env


def env_creator(env_config=None):
    """
    RLlib environment creator.
    """
    return CC4Env()


def register_cc4_env():
    """
    Register the environment with RLlib.
    Safe to call multiple times.
    """
    register_env("CC4", lambda config: env_creator(config))